//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terrarium.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string SerialPortName {
            get {
                return ((string)(this["SerialPortName"]));
            }
            set {
                this["SerialPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4800")]
        public int SerialPortBoude {
            get {
                return ((int)(this["SerialPortBoude"]));
            }
            set {
                this["SerialPortBoude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int SerialDataBits {
            get {
                return ((int)(this["SerialDataBits"]));
            }
            set {
                this["SerialDataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SerialPortParity {
            get {
                return ((string)(this["SerialPortParity"]));
            }
            set {
                this["SerialPortParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SerialStopBits {
            get {
                return ((string)(this["SerialStopBits"]));
            }
            set {
                this["SerialStopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SerialHandshake {
            get {
                return ((string)(this["SerialHandshake"]));
            }
            set {
                this["SerialHandshake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("74600")]
        public int SerialBaudCustome {
            get {
                return ((int)(this["SerialBaudCustome"]));
            }
            set {
                this["SerialBaudCustome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sidePannelHide {
            get {
                return ((bool)(this["sidePannelHide"]));
            }
            set {
                this["sidePannelHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool rtb_Rx_AutoScroll {
            get {
                return ((bool)(this["rtb_Rx_AutoScroll"]));
            }
            set {
                this["rtb_Rx_AutoScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte dfp_Rx_State {
            get {
                return ((byte)(this["dfp_Rx_State"]));
            }
            set {
                this["dfp_Rx_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color rtb_Rx_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["rtb_Rx_FontColor"]));
            }
            set {
                this["rtb_Rx_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font rtb_Rx_FontProperty {
            get {
                return ((global::System.Drawing.Font)(this["rtb_Rx_FontProperty"]));
            }
            set {
                this["rtb_Rx_FontProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50,50,50\r\n")]
        public string rtb_Rx_BackgroundColor {
            get {
                return ((string)(this["rtb_Rx_BackgroundColor"]));
            }
            set {
                this["rtb_Rx_BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cb_Sort {
            get {
                return ((bool)(this["cb_Sort"]));
            }
            set {
                this["cb_Sort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal nmn_ByteSort {
            get {
                return ((decimal)(this["nmn_ByteSort"]));
            }
            set {
                this["nmn_ByteSort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool panelMacroStatus {
            get {
                return ((bool)(this["panelMacroStatus"]));
            }
            set {
                this["panelMacroStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string macroPanelConfFileLocation {
            get {
                return ((string)(this["macroPanelConfFileLocation"]));
            }
            set {
                this["macroPanelConfFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cb_TxMacroSend {
            get {
                return ((bool)(this["cb_TxMacroSend"]));
            }
            set {
                this["cb_TxMacroSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cb_Tx_Hex {
            get {
                return ((bool)(this["cb_Tx_Hex"]));
            }
            set {
                this["cb_Tx_Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isPanelSettingsHiden {
            get {
                return ((bool)(this["isPanelSettingsHiden"]));
            }
            set {
                this["isPanelSettingsHiden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isPanelMacroHiden {
            get {
                return ((bool)(this["isPanelMacroHiden"]));
            }
            set {
                this["isPanelMacroHiden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBtnPannelPortSettingsHiden {
            get {
                return ((bool)(this["isBtnPannelPortSettingsHiden"]));
            }
            set {
                this["isBtnPannelPortSettingsHiden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBtnPanelReceivingHiden {
            get {
                return ((bool)(this["isBtnPanelReceivingHiden"]));
            }
            set {
                this["isBtnPanelReceivingHiden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBtnPanelTransmitingHiden {
            get {
                return ((bool)(this["isBtnPanelTransmitingHiden"]));
            }
            set {
                this["isBtnPanelTransmitingHiden"] = value;
            }
        }
    }
}
